---
- hosts: localhost
  connection: local
  become: true
  vars_files:
    - vars/main.yml
  tasks:
    #- include: tasks/apt.yml
    #- include: tasks/awscli.yml
    #- include: tasks/helm.yml
    #- include: tasks/kubectl.yml
    #- include: tasks/kubie.yml
    #- include: tasks/packer.yml
    - include: tasks/python.yml
    #- include: tasks/pip.yml
    #- include: tasks/terraform.yml
    #- include: tasks/tfenv.yml
    #- include: tasks/vscode.yml