---
- name: Descarga de helm version "{{ helm_version }}"
  get_url:
    url: "{{ helm_download_url }}"
    dest: "{{ tmp_dir }}{{ mnt_path }}"
  register: download_helm

- name: Descomprimir  helm
  unarchive:
    src: "{{ tmp_dir }}{{ mnt_path }}/{{ helm_download_url | basename }}"
    dest: "{{ tmp_dir }}{{ mnt_path }}"
    remote_src: yes
  when: download_helm.changed

- name: Alojar helm en /usr/local/bin
  copy:
    src: "{{ tmp_dir }}{{ mnt_path }}/linux-amd64/helm"
    dest: "{{ binary_path }}"
    remote_src: yes
    mode: "0755"
